export const USERS = [
  {
    id: 1,
    username: "alice",
    password: "password1",
    name: "Alice Johnson",
    email: "alice@example.com",
  },
  {
    id: 2,
    username: "bob",
    password: "h",
    name: "Bob Smith",
    email: "bob@example.com",
  },
];

export const TASKS = [
  { id: 1,   userId: 1, title: "Buy groceries",                        done: false },
  { id: 2,   userId: 1, title: "Read a book",                          done: true  },
  { id: 3,   userId: 1, title: "Exercise",                             done: false },
  { id: 4,   userId: 1, title: "Schedule dentist appointment",         done: false },
  { id: 5,   userId: 1, title: "Pay utility bills",                    done: true  },
  { id: 6,   userId: 1, title: "Clean the kitchen",                    done: false },
  { id: 7,   userId: 1, title: "Water the plants",                     done: true  },
  { id: 8,   userId: 1, title: "Reply to emails",                      done: false },
  { id: 9,   userId: 1, title: "Organise desk",                        done: false },
  { id: 10,  userId: 1, title: "Take out the trash",                   done: true  },
  { id: 11,  userId: 1, title: "Update resume",                        done: false },
  { id: 12,  userId: 1, title: "Back up photos",                       done: false },
  { id: 13,  userId: 1, title: "Call mom",                             done: true  },
  { id: 14,  userId: 1, title: "Book flight tickets",                  done: false },
  { id: 15,  userId: 1, title: "Renew gym membership",                 done: false },
  { id: 16,  userId: 1, title: "Cook meal prep for the week",          done: true  },
  { id: 17,  userId: 1, title: "Review monthly budget",                done: false },
  { id: 18,  userId: 1, title: "Fix the leaky tap",                    done: false },
  { id: 19,  userId: 1, title: "Donate old clothes",                   done: true  },
  { id: 20,  userId: 1, title: "Learn 10 new vocabulary words",        done: false },
  { id: 21,  userId: 1, title: "Stretch for 15 minutes",               done: false },
  { id: 22,  userId: 1, title: "Read the news",                        done: true  },
  { id: 23,  userId: 1, title: "Clean bathroom",                       done: false },
  { id: 24,  userId: 1, title: "Watch online course lecture",          done: false },
  { id: 25,  userId: 1, title: "Grocery list planning",                done: true  },
  { id: 26,  userId: 1, title: "Send birthday card",                   done: false },
  { id: 27,  userId: 1, title: "Cancel unused subscriptions",          done: false },
  { id: 28,  userId: 1, title: "Walk 10,000 steps",                    done: true  },
  { id: 29,  userId: 1, title: "Tidy living room",                     done: false },
  { id: 30,  userId: 1, title: "Write journal entry",                  done: false },
  { id: 31,  userId: 1, title: "Research new laptop",                  done: true  },
  { id: 32,  userId: 1, title: "Fix broken shelf",                     done: false },
  { id: 33,  userId: 1, title: "Meditate for 10 minutes",              done: false },
  { id: 34,  userId: 1, title: "Declutter wardrobe",                   done: true  },
  { id: 35,  userId: 1, title: "Plan weekend trip",                    done: false },
  { id: 36,  userId: 1, title: "Buy birthday gift",                    done: false },
  { id: 37,  userId: 1, title: "Floss teeth",                          done: true  },
  { id: 38,  userId: 1, title: "Review work presentation",             done: false },
  { id: 39,  userId: 1, title: "Pick up prescription",                 done: false },
  { id: 40,  userId: 1, title: "Sort recycling",                       done: true  },
  { id: 41,  userId: 1, title: "Read 30 pages",                        done: false },
  { id: 42,  userId: 1, title: "Iron clothes",                         done: false },
  { id: 43,  userId: 1, title: "Check car tyre pressure",              done: true  },
  { id: 44,  userId: 1, title: "Update phone OS",                      done: false },
  { id: 45,  userId: 1, title: "Prepare tax documents",                done: false },
  { id: 46,  userId: 1, title: "Feed neighbour's cat",                 done: true  },
  { id: 47,  userId: 1, title: "Unsubscribe from spam emails",         done: false },
  { id: 48,  userId: 1, title: "Write weekly review",                  done: false },
  { id: 49,  userId: 1, title: "Oil squeaky door hinge",               done: true  },
  { id: 50,  userId: 1, title: "Defrost freezer",                      done: false },
  { id: 51,  userId: 1, title: "Research health insurance options",    done: false },
  { id: 52,  userId: 1, title: "Set up automatic savings transfer",    done: true  },
  { id: 53,  userId: 1, title: "Clean out car",                        done: false },
  { id: 54,  userId: 1, title: "Practise guitar for 20 minutes",       done: false },
  { id: 55,  userId: 1, title: "Make dentist appointment",             done: true  },
  { id: 56,  userId: 1, title: "Sort out spare room",                  done: false },
  { id: 57,  userId: 1, title: "Buy new running shoes",                done: false },
  { id: 58,  userId: 1, title: "Return library books",                 done: true  },
  { id: 59,  userId: 1, title: "Plan meals for next week",             done: false },
  { id: 60,  userId: 1, title: "Check smoke alarm batteries",          done: false },
  { id: 61,  userId: 1, title: "Paint fence",                          done: true  },
  { id: 62,  userId: 1, title: "Catch up with old friend",             done: false },
  { id: 63,  userId: 1, title: "Sign up for cooking class",            done: false },
  { id: 64,  userId: 1, title: "Clean windows",                        done: true  },
  { id: 65,  userId: 1, title: "Set up 2FA on all accounts",           done: false },
  { id: 66,  userId: 1, title: "Read nutrition labels while shopping", done: false },
  { id: 67,  userId: 1, title: "Repair torn bag",                      done: true  },
  { id: 68,  userId: 1, title: "Log daily water intake",               done: false },
  { id: 69,  userId: 1, title: "Book car service",                     done: false },
  { id: 70,  userId: 1, title: "Vacuum all rooms",                     done: true  },
  { id: 71,  userId: 1, title: "Tidy cables behind desk",              done: false },
  { id: 72,  userId: 1, title: "Research best savings account",        done: false },
  { id: 73,  userId: 1, title: "Practise mindfulness",                 done: true  },
  { id: 74,  userId: 1, title: "Write thank-you note",                 done: false },
  { id: 75,  userId: 1, title: "Mow the lawn",                         done: false },
  { id: 76,  userId: 1, title: "Update emergency contacts",            done: true  },
  { id: 77,  userId: 1, title: "Sort out old paperwork",               done: false },
  { id: 78,  userId: 1, title: "Try a new recipe",                     done: false },
  { id: 79,  userId: 1, title: "Review insurance policy",              done: true  },
  { id: 80,  userId: 1, title: "Clean fridge",                         done: false },
  { id: 81,  userId: 1, title: "Charge all devices",                   done: false },
  { id: 82,  userId: 1, title: "Watch documentary",                    done: true  },
  { id: 83,  userId: 1, title: "Organise digital files",               done: false },
  { id: 84,  userId: 1, title: "Schedule eye test",                    done: false },
  { id: 85,  userId: 1, title: "Prepare for job interview",            done: true  },
  { id: 86,  userId: 1, title: "Learn keyboard shortcut",              done: false },
  { id: 87,  userId: 1, title: "Trim houseplants",                     done: false },
  { id: 88,  userId: 1, title: "Shred old documents",                  done: true  },
  { id: 89,  userId: 1, title: "Update will",                          done: false },
  { id: 90,  userId: 1, title: "Bleach grout in bathroom",             done: false },
  { id: 91,  userId: 1, title: "Swap out seasonal clothing",           done: true  },
  { id: 92,  userId: 1, title: "Research pension options",             done: false },
  { id: 93,  userId: 1, title: "Clean microwave",                      done: false },
  { id: 94,  userId: 1, title: "Call utility provider about bill",     done: true  },
  { id: 95,  userId: 1, title: "Set up morning routine",               done: false },
  { id: 96,  userId: 1, title: "Repair bicycle tyre",                  done: false },
  { id: 97,  userId: 1, title: "Reorganise bookshelf",                 done: true  },
  { id: 98,  userId: 1, title: "Write blog post draft",                done: false },
  { id: 99,  userId: 1, title: "Delete unused apps",                   done: false },
  { id: 100, userId: 1, title: "Plan next month's goals",              done: true  },
  { id: 101, userId: 2, title: "Fix the sink",                         done: false },
  { id: 102, userId: 2, title: "Call the dentist",                     done: true  },
  { id: 103, userId: 2, title: "Write a blog post",                    done: false },
];
